# version: '3'
# services:
#   db:
#     image: postgres:13
#     ports:
#       - 5435:5432
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 123
#       POSTGRES_DB: nestjs
#   test-db:
#     image: postgres:13
#     ports:
#       - 5436:5432
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 123
#       POSTGRES_DB: nestjs

# docker compose up

version: '3'
services:
  app:
    image: islomdev/nest-wallet-app
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:123@db:5432/nestjs
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
  # test-db:
  #   image: postgres:13
  #   ports:
  #     - 5436:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_DB: nestjs
