version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgress
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
  # app: 
  #   build: './' 
  #   image: wallet-app
  #   container_name: wallet-app
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - .env_deployment